# Project 2: Build Decision Tree for Attrition Rate Analysis

DV - "Attrition"

IDV - Output of RF Algorithm


In [1]:
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn import preprocessing

In [4]:
att_train=pd.read_csv("general_data.csv")
att_train.head(5)

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   51        No      Travel_Rarely                   Sales                 6   
1   31       Yes  Travel_Frequently  Research & Development                10   
2   32        No  Travel_Frequently  Research & Development                17   
3   38        No         Non-Travel  Research & Development                 2   
4   32        No      Travel_Rarely  Research & Development                10   

   Education EducationField  EmployeeCount  EmployeeID  Gender  ...  \
0          2  Life Sciences              1           1  Female  ...   
1          1  Life Sciences              1           2  Female  ...   
2          4          Other              1           3    Male  ...   
3          5  Life Sciences              1           4    Male  ...   
4          1        Medical              1           5    Male  ...   

   NumCompaniesWorked Over18 PercentSalaryHike  StandardHours  \
0                 1.0      Y                11              8   
1                 0.0      Y                23              8   
2                 1.0      Y                15              8   
3                 3.0      Y                11              8   
4                 4.0      Y                12              8   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear  YearsAtCompany  \
0                 0               1.0                      6               1   
1                 1               6.0                      3               5   
2                 3               5.0                      2               5   
3                 3              13.0                      5               8   
4                 2               9.0                      2               6   

   YearsSinceLastPromotion  YearsWithCurrManager  
0                        0                     0  
1                        1                     4  
2                        0                     3  
3                        7                     5  
4                        0                     4  

[5 rows x 24 columns]

In [5]:
att_train.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount', 'EmployeeID', 'Gender',
       'JobLevel', 'JobRole', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'Over18', 'PercentSalaryHike', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'YearsAtCompany', 'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

# Random Forest for selecting important features

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
att_train.isna().sum()

Age                         0
Attrition                   0
BusinessTravel              0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeID                  0
Gender                      0
JobLevel                    0
JobRole                     0
MaritalStatus               0
MonthlyIncome               0
NumCompaniesWorked         19
Over18                      0
PercentSalaryHike           0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           9
TrainingTimesLastYear       0
YearsAtCompany              0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

There are null values in Num of Companies Worked and total working years. SO, as they are continous we will replace it by mean.

In [30]:
new_var = np.where(att_train['NumCompaniesWorked'].isnull(),att_train['NumCompaniesWorked'].mean(),att_train['NumCompaniesWorked'])
att_train['NumCompaniesWorked']=new_var
new_var2 = np.where(att_train['TotalWorkingYears'].isnull(),att_train['TotalWorkingYears'].mean(),att_train['TotalWorkingYears'])
att_train['TotalWorkingYears']=new_var
att_train.isnull().sum().sum()

0

In [31]:
objList = att_train.select_dtypes(include = "object").columns
print (objList)

Index([], dtype='object')


In [32]:
#Label Encoding for object to numeric conversion
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for feat in objList:
    att_train[feat] = le.fit_transform(att_train[feat].astype(str))

att_train.head(10)

Age  Attrition  BusinessTravel  Department  DistanceFromHome  Education  \
0   51          0               2           2                 6          2   
1   31          1               1           1                10          1   
2   32          0               1           1                17          4   
3   38          0               0           1                 2          5   
4   32          0               2           1                10          1   
5   46          0               2           1                 8          3   
6   28          1               2           1                11          2   
7   29          0               2           1                18          3   
8   31          0               2           1                 1          3   
9   25          0               0           1                 7          4   

   EducationField  EmployeeCount  EmployeeID  Gender  ...  NumCompaniesWorked  \
0               1              1           1       0  ...                 1.0   
1               1              1           2       0  ...                 0.0   
2               4              1           3       1  ...                 1.0   
3               1              1           4       1  ...                 3.0   
4               3              1           5       1  ...                 4.0   
5               1              1           6       0  ...                 3.0   
6               3              1           7       1  ...                 2.0   
7               1              1           8       1  ...                 2.0   
8               1              1           9       1  ...                 0.0   
9               3              1          10       0  ...                 1.0   

   Over18  PercentSalaryHike  StandardHours  StockOptionLevel  \
0       0                 11              8                 0   
1       0                 23              8                 1   
2       0                 15              8                 3   
3       0                 11              8                 3   
4       0                 12              8                 2   
5       0                 13              8                 0   
6       0                 20              8                 1   
7       0                 22              8                 3   
8       0                 21              8                 0   
9       0                 13              8                 1   

   TotalWorkingYears  TrainingTimesLastYear  YearsAtCompany  \
0                1.0                      6               1   
1                0.0                      3               5   
2                1.0                      2               5   
3                3.0                      5               8   
4                4.0                      2               6   
5                3.0                      5               7   
6                2.0                      2               0   
7                2.0                      2               0   
8                0.0                      2               9   
9                1.0                      2               6   

   YearsSinceLastPromotion  YearsWithCurrManager  
0                        0                     0  
1                        1                     4  
2                        0                     3  
3                        7                     5  
4                        0                     4  
5                        7                     7  
6                        0                     0  
7                        0                     0  
8                        7                     8  
9                        1                     5  

[10 rows x 24 columns]

In [33]:
rf_model=RandomForestClassifier(n_estimators=1000,max_features=2,oob_score=True)

In [34]:
features=['Age','BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EmployeeCount', 'EmployeeID', 'Gender',
       'JobLevel', 'JobRole', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'Over18', 'PercentSalaryHike', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'YearsAtCompany', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

In [35]:
rf_model.fit(X=att_train[features],y=att_train['Attrition'])

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features=2,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [36]:
print(rf_model.oob_score_)

0.999546485260771


So, the model is 99.95% accurate.

In [38]:
for feature,imp in zip(features,rf_model.feature_importances_):
    print(feature,imp)

Age 0.1012756305872713
BusinessTravel 0.028006092743498075
Department 0.026462545638167526
DistanceFromHome 0.06963990245560811
Education 0.04017390719861266
EducationField 0.041887640723586285
EmployeeCount 0.0
EmployeeID 0.0384569295196118
Gender 0.01768735795986247
JobLevel 0.037117033650208166
JobRole 0.05535031464771784
MaritalStatus 0.039721854064089075
MonthlyIncome 0.09089075910561521
NumCompaniesWorked 0.04637718466433975
Over18 0.0
PercentSalaryHike 0.06470037281926573
StandardHours 0.0
StockOptionLevel 0.03378051899953105
TotalWorkingYears 0.04541496961614397
TrainingTimesLastYear 0.044337915625801534
YearsAtCompany 0.07573083734570164
YearsSinceLastPromotion 0.043309662711307866
YearsWithCurrManager 0.05967856992405987


In this Dataset: Age,DistanceFromHome,MonthlyIncome,PercentSalaryHike,YearsAtCompany Can be considered as imp. features.

In [39]:
imp_features=['Age', 'DistanceFromHome', 'MonthlyIncome','PercentSalaryHike','YearsAtCompany']
rf_model.fit(X=att_train[imp_features],y=att_train['Attrition'])
print(rf_model.oob_score_)

1.0


Thus, now the model is 100% accurate.

# Classification

In [40]:
tree_model = tree.DecisionTreeClassifier(max_depth=8)
features=['Age', 'DistanceFromHome', 'MonthlyIncome','PercentSalaryHike','YearsAtCompany']
tree_model.fit(X=att_train[features],y=att_train['Attrition'])

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=8, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [41]:
with open('att_Dtree.dot','w') as f:
    f=tree.export_graphviz(tree_model,feature_names=features,out_file=f)
    

Inferences from Classification:

In [42]:
r=tree.export_text(tree_model,feature_names=features)
print(r)

|--- YearsAtCompany <= 1.50
|   |--- Age <= 33.50
|   |   |--- MonthlyIncome <= 112610.00
|   |   |   |--- Age <= 22.50
|   |   |   |   |--- MonthlyIncome <= 23140.00
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- MonthlyIncome >  23140.00
|   |   |   |   |   |--- Age <= 18.50
|   |   |   |   |   |   |--- DistanceFromHome <= 4.00
|   |   |   |   |   |   |   |--- PercentSalaryHike <= 20.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- PercentSalaryHike >  20.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- DistanceFromHome >  4.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- Age >  18.50
|   |   |   |   |   |   |--- MonthlyIncome <= 106255.00
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- MonthlyIncome >  106255.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |--- Age >  22.50
|   |   |   |   |--- MonthlyIncome <= 72530.00
|   |   |   |   |   |--- DistanceFromHome

Some of the inferences:
   
1) The employees with YearsAt Compant <=1.5, Age <=22.5 and MonthlyIncome <= 23140.00 : Attrition "NO"

2)The employees with YearsAtCompany <= 1.50, Age <= 18.50, DistanceFromHome <= 4.00 and PercentSalaryHike <= 20.0 : Attrition "Yes" , whereas PercentSalaryHike > 20.0: Attrition "No".

3)The employees with Age <= 33.50, DistanceFromHome <= 7.50, MonthlyIncome <= 59150.00, PercentSalaryHike <= 13.50 and  1.5<YearsAtCompany <= 2.50: Attrition "Yes" 

4)The employees with Age <= 33.50, DistanceFromHome <= 7.50, MonthlyIncome <= 59150.00, PercentSalaryHike <= 13.50 and YearsAtCompany >  2.50: Attrition "No"..etc

    